[package]
name = "reference_cycles"
version = "0.1.0"
edition = "2021"
authors = ["Vivek <vivek.yadav472@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
