[package]
name = "testing"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
criterion = { version = "0.4", features = ["html_reports"] }

[dependencies]

[[bench]]
name = "somename"
harness = false
